{% set name = "BindsNET" %}
{% set version = "0.2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}
  
source:
  git_url: https://github.com/{{ name }}/{{ name }}.git
  git_rev: 0.2.7-conda
  git_depth: 1 # (Defaults to -1/not shallow)
  # path: ../.

build: 
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  

requirements:   
  host:
    - python >=3.5
    - pip
    - setuptools >=39.0.1
    - scipy >=1.1.0
    - numpy >=1.14.2
    - pytorch >=1.3.0
    - torchvision >=0.3.0
    - tqdm >=4.19.9
    - matplotlib >=2.1.0
    - gym
    - scikit-image >=0.13.1
    - scikit-learn >=0.19.1
    - opencv >=3.4.0.12
    - sphinx_rtd_theme >=0.4.1
    - pytest >=3.4.0
    - cython >=0.28.5
    - pandas >=1.0.0
    - pillow >=6,<7
    - tensorboardx >=1.7
        
  run:
    - python >=3.5
    - pip
    - setuptools >=39.0.1
    - scipy >=1.1.0
    - numpy >=1.14.2
    - pytorch >=1.3.0
    - torchvision >=0.3.0
    - tqdm >=4.19.9
    - matplotlib >=2.1.0
    - gym
    - scikit-image >=0.13.1
    - scikit-learn >=0.19.1
    - opencv >=3.4.0.12
    - sphinx_rtd_theme >=0.4.1
    - pytest >=3.4.0
    - cython >=0.28.5
    - pandas >=1.0.0
    - pillow >=6,<7
    - tensorboardx >=1.7

test:
     imports:
        - bindsnet
        - bindsnet.analysis
        - bindsnet.conversion
        - bindsnet.datasets
        - bindsnet.encoding
        - bindsnet.environment
        - bindsnet.evaluation
        - bindsnet.learning
        - bindsnet.models
        - bindsnet.network
        - bindsnet.pipeline
        - bindsnet.preprocessing

        
about:
  home: https://github.com/BindsNET/bindsnet
  license: AGPL-3.0
  summary: Simulation of spiking neural networks (SNNs) using PyTorch.

extra:
  recipe-maintainers:
    - Hananel-Hazan
